name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions-rs/toolchain@v1.0.6
      with:
          toolchain: nightly
    - name: Build
      uses: actions-rs/cargo@v1
      run: cargo build --verbose