name: zflow_runtime

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Protoc
    - uses: arduino/setup-protoc@v3
    - name: Setup actions
    - uses: actions/checkout@v3
    - name: Build quickjs runner
      run:  cd crates/zflow_js_runner && cargo build  --release && cp ./bin/release/libzflow_js_runner.so ./bin/libzflow_js_runner.so
    - name: Run runtime tests
      run: ZFLOW_QUICKJS_RUNNER_LIB=../zflow_js_runner/bin/libzflow_js_runner.so cargo test --package zflow_runtime --verbose -- --skip network_test
    - name: Run network tests 
      run: ZFLOW_QUICKJS_RUNNER_LIB=../zflow_js_runner/bin/libzflow_js_runner.so cargo test --package zflow_runtime --verbose  --lib -- 'network_test::tests::test_network'
